CREATE TABLE IF NOT EXISTS Orders(
    OrderID INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    CustomerID CHAR(5) REFERENCES Customers(CustomerID) NOT NULL,
    EmployeeID INTEGER REFERENCES Employees(EmployeeID) NOT NULL,
    OrderDate TIMESTAMP NOT NULL,
    RequiredDate TIMESTAMP NOT NULL,
    ShippedDate TIMESTAMP,
    ShipVia INTEGER REFERENCES Shippers(ShipperID) NOT NULL,
    Freight DECIMAL(15, 4) NOT NULL,
    ShipName VARCHAR(40) NOT NULL,
    ShipAdress VARCHAR(60) NOT NULL,
    ShipCity VARCHAR(15) NOT NULL,
    ShipRegio VARCHAR(15),
    ShipPostalCode VARCHAR(10),
    ShipCountry VARCHAR(15) NOT NULL
);